### ISSUE TITLE
小姐姐好厉害啊！文章提出了一个很有趣的问题！

### ISSUE THREAD

**Issue by bright1993ff66** [luofuli/Fine-grained-Sentiment-Transfer#2]
期待code。。。
我觉得基于这篇paper，是不是可以比如说做一些其他工作比如image captioning的话，现在的模型都没有什么含有sentiment的captioning。。。
我们是不是可以利用社交网络的数据，很多tweets不光有text information还有user发的图片，能不能通过text information generate出来sentiment embedding，然后让image caption model产生一些带有sentiment的captioning? 
不知道是不是可行😆

**Comment by bright1993ff66** [comment]
大概像这样? 
![Blank Diagram](https://user-images.githubusercontent.com/29517359/64470625-0a907c80-d179-11e9-9f9f-ff304ad4aa22.png)

**Comment by luofuli** [comment]
不错的想法！但是有个问题是，社交领域的文字有很多不是描述图片的，比如表情包图片这些等等。所以可能跟image caption还不太一致。不过值得一试。

**Comment by bright1993ff66** [comment]
嗯嗯，但是这里我们提取的只是sentiment。想把sentiment的信息加入到image captioning中~
小姐姐说的那种，今年ACL有篇文章有讲到: 
[Informative Image Captioning with External Sources of Information](https://arxiv.org/abs/1906.08876)
