### ISSUE TITLE
error when running main.py in regressor and seq2sentiseq

### ISSUE THREAD

**Issue by LeiShenVictoria** [luofuli/Fine-grained-Sentiment-Transfer#4]
Hi, 
An error occurs when I run main.py in regressor.
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unquoted fields cannot have quotes/CRLFs inside
	 [[{{node DecodeCSV}}]]
	 [[node IteratorGetNext (defined at main.py:177) ]]

**Comment by aflah02** [comment]
Hey, did you get this error when you changed data sources? I got a similar error as well was wondering if you were able to resolve it
