### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by huxx499** [luofuli/Fine-grained-Sentiment-Transfer#5]
The paper says "We randomly hold 630K for training, 10K for validation, and 500 for testing."
However, i found that there only 240K sentences in train.txt and 31485 sentences in dev.txt. 
Could you explain why this happened? Thank you.

**Comment by luofuli** [comment]
We have done some data cleaning when released the code. You can re-train the model on the released data or your own data to get the comparable test results.
