### ISSUE TITLE
Question on the outputs (yelp)

### ISSUE THREAD

**Issue by SenZHANG-GitHub** [luofuli/Fine-grained-Sentiment-Transfer#6]
Thanks for your interesting work! May I ask whether there are some explainations for the output format? There are five outputs for each sentence and I'm wondering which models correspond to those outputs : )

**Comment by luofuli** [comment]
The target sentiment of the five outputs are `0.1, 0.3, 0.5, 0.7, 0.9`

**Comment by SenZHANG-GitHub** [comment]
> The target sentiment of the five outputs are `0.1, 0.3, 0.5, 0.7, 0.9`

Thanks a lot for your explaination! : )
